#!/bin/bash

# Test script for LaTeX PDF backend
echo "Testing LaTeX PDF Backend..."
echo ""

# Test health endpoint
echo "1. Testing /health endpoint..."
curl -s http://localhost:3001/health | python3 -m json.tool
echo ""
echo ""

# Test PDF generation
echo "2. Testing /render endpoint..."
curl -X POST http://localhost:3001/render \
  -H "Content-Type: application/json" \
  -d '{
    "latex": "\\documentclass{article}\n\\usepackage[margin=1in]{geometry}\n\\begin{document}\n\\title{Test Document}\n\\author{LaTeX Service}\n\\date{\\today}\n\\maketitle\n\\section{Introduction}\nThis is a test PDF generated by the LaTeX service.\n\\section{Features}\n\\begin{itemize}\n\\item Real LaTeX compilation\n\\item Security features\n\\item Auto cleanup\n\\end{itemize}\n\\end{document}"
  }' \
  --output test-output.pdf

if [ -f "test-output.pdf" ]; then
  echo "✓ PDF generated successfully: test-output.pdf"
  echo "File size: $(du -h test-output.pdf | cut -f1)"
  open test-output.pdf 2>/dev/null || xdg-open test-output.pdf 2>/dev/null || echo "PDF saved as test-output.pdf"
else
  echo "✗ PDF generation failed"
fi

echo ""
echo "Test complete!"
