// components/ResultLatex.jsx
import React, { useEffect, useState } from "react";

export function ResultLatex({ output, styles }) {
    const [source, setSource] = useState(output || "");

    // When a new webhook response arrives, reset editor content
    useEffect(() => {
        setSource(output || "");
    }, [output]);

    return (
        <div style={styles.latexInner}>
            <div style={styles.latexHeaderRow}>
                <div>
                    <h3 style={styles.sectionTitle}>LaTeX Resume Editor</h3>
                    <p style={styles.sectionNote}>
                        Left: editable LaTeX generated by the AI agent. Right: a visual
                        preview styled like a PDF page.
                    </p>
                </div>
            </div>

            <div style={styles.latexGrid}>
                {/* Left – code editor */}
                <div style={styles.latexEditorPane}>
                    <label style={styles.label}>LaTeX source</label>
                    <textarea
                        value={source}
                        onChange={(e) => setSource(e.target.value)}
                        style={styles.latexTextarea}
                    />
                </div>

                {/* Right – visual preview (text-based “PDF” look for now) */}
                <div style={styles.latexPreviewPane}>
                    <div style={styles.latexPreviewPage}>
                        <div style={styles.latexPreviewHeader}>
                            <span style={styles.latexPreviewBadge}>Preview</span>
                            <span style={styles.latexPreviewHint}>
                                This is a live preview of the LaTeX source. Full PDF
                                rendering can be wired up later.
                            </span>
                        </div>
                        <pre style={styles.latexPreviewCode}>{source}</pre>
                    </div>
                </div>
            </div>
        </div>
    );
}